lolautruche_payline_notification:
    path:     /payline/notification
    controller: Lolautruche\PaylineBundle\Controller\PaylineController::paymentNotificationAction

lolautruche_payline_back_to_shop:
    path:     /payline/back-to-shop
    controller: Lolautruche\PaylineBundle\Controller\PaylineController::backToShopAction
